[package]
name = "signatures"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
num-bigint = "0.4"
eyre = "*"
sha2 = "*"
hex = "*"
glass_pumpkin = "1.0"
nalgebra = "*"
openssl = "0.10"
rsa = "0.7.0"
der = "0.6"
secp256k1 = { version = "0.30.0", features = ["hashes"] }